// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtransformer__Syms.h"


void Vtransformer___024root__trace_chg_0_sub_0(Vtransformer___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtransformer___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_chg_0\n"); );
    // Init
    Vtransformer___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtransformer___024root*>(voidSelf);
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtransformer___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtransformer___024root__trace_chg_0_sub_0(Vtransformer___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_chg_0_sub_0\n"); );
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[1U]))) {
        bufp->chgSData(oldp+0,(vlSelfRef.transformer__DOT__qk00_raw),16);
        bufp->chgSData(oldp+1,(vlSelfRef.transformer__DOT__qk01_raw),16);
        bufp->chgSData(oldp+2,(vlSelfRef.transformer__DOT__qk10_raw),16);
        bufp->chgSData(oldp+3,(vlSelfRef.transformer__DOT__qk11_raw),16);
        bufp->chgSData(oldp+4,(vlSelfRef.transformer__DOT__qk00),16);
        bufp->chgSData(oldp+5,(vlSelfRef.transformer__DOT__qk01),16);
        bufp->chgSData(oldp+6,(vlSelfRef.transformer__DOT__qk10),16);
        bufp->chgSData(oldp+7,(vlSelfRef.transformer__DOT__qk11),16);
        bufp->chgSData(oldp+8,(vlSelfRef.transformer__DOT__u_mma__DOT__m00_0),16);
        bufp->chgSData(oldp+9,(vlSelfRef.transformer__DOT__u_mma__DOT__m00_1),16);
        bufp->chgSData(oldp+10,(vlSelfRef.transformer__DOT__u_mma__DOT__m01_0),16);
        bufp->chgSData(oldp+11,(vlSelfRef.transformer__DOT__u_mma__DOT__m01_1),16);
        bufp->chgSData(oldp+12,(vlSelfRef.transformer__DOT__u_mma__DOT__m10_0),16);
        bufp->chgSData(oldp+13,(vlSelfRef.transformer__DOT__u_mma__DOT__m10_1),16);
        bufp->chgSData(oldp+14,(vlSelfRef.transformer__DOT__u_mma__DOT__m11_0),16);
        bufp->chgSData(oldp+15,(vlSelfRef.transformer__DOT__u_mma__DOT__m11_1),16);
        bufp->chgBit(oldp+16,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__sign));
        bufp->chgCData(oldp+17,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__exponent),6);
        bufp->chgSData(oldp+18,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__mantissa),10);
        bufp->chgCData(oldp+19,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__exponentA),6);
        bufp->chgCData(oldp+20,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__exponentB),6);
        bufp->chgSData(oldp+21,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__fractionA),11);
        bufp->chgSData(oldp+22,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__fractionB),11);
        bufp->chgSData(oldp+23,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__fraction),11);
        bufp->chgCData(oldp+24,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__shiftAmount),8);
        bufp->chgBit(oldp+25,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__cout));
        bufp->chgBit(oldp+26,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__sign));
        bufp->chgCData(oldp+27,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__exponent),6);
        bufp->chgSData(oldp+28,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__mantissa),10);
        bufp->chgCData(oldp+29,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__exponentA),6);
        bufp->chgCData(oldp+30,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__exponentB),6);
        bufp->chgSData(oldp+31,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__fractionA),11);
        bufp->chgSData(oldp+32,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__fractionB),11);
        bufp->chgSData(oldp+33,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__fraction),11);
        bufp->chgCData(oldp+34,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__shiftAmount),8);
        bufp->chgBit(oldp+35,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__cout));
        bufp->chgBit(oldp+36,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__sign));
        bufp->chgCData(oldp+37,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__exponent),6);
        bufp->chgSData(oldp+38,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__mantissa),10);
        bufp->chgCData(oldp+39,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__exponentA),6);
        bufp->chgCData(oldp+40,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__exponentB),6);
        bufp->chgSData(oldp+41,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__fractionA),11);
        bufp->chgSData(oldp+42,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__fractionB),11);
        bufp->chgSData(oldp+43,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__fraction),11);
        bufp->chgCData(oldp+44,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__shiftAmount),8);
        bufp->chgBit(oldp+45,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__cout));
        bufp->chgBit(oldp+46,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__sign));
        bufp->chgCData(oldp+47,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__exponent),6);
        bufp->chgSData(oldp+48,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__mantissa),10);
        bufp->chgCData(oldp+49,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__exponentA),6);
        bufp->chgCData(oldp+50,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__exponentB),6);
        bufp->chgSData(oldp+51,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__fractionA),11);
        bufp->chgSData(oldp+52,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__fractionB),11);
        bufp->chgSData(oldp+53,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__fraction),11);
        bufp->chgCData(oldp+54,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__shiftAmount),8);
        bufp->chgBit(oldp+55,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__cout));
        bufp->chgBit(oldp+56,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__sign));
        bufp->chgCData(oldp+57,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__exponent),6);
        bufp->chgSData(oldp+58,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__mantissa),10);
        bufp->chgSData(oldp+59,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__fractionA),11);
        bufp->chgSData(oldp+60,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__fractionB),11);
        bufp->chgIData(oldp+61,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__fraction),22);
        bufp->chgBit(oldp+62,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__sign));
        bufp->chgCData(oldp+63,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__exponent),6);
        bufp->chgSData(oldp+64,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__mantissa),10);
        bufp->chgSData(oldp+65,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__fractionA),11);
        bufp->chgSData(oldp+66,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__fractionB),11);
        bufp->chgIData(oldp+67,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__fraction),22);
        bufp->chgBit(oldp+68,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__sign));
        bufp->chgCData(oldp+69,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__exponent),6);
        bufp->chgSData(oldp+70,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__mantissa),10);
        bufp->chgSData(oldp+71,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__fractionA),11);
        bufp->chgSData(oldp+72,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__fractionB),11);
        bufp->chgIData(oldp+73,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__fraction),22);
        bufp->chgBit(oldp+74,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__sign));
        bufp->chgCData(oldp+75,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__exponent),6);
        bufp->chgSData(oldp+76,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__mantissa),10);
        bufp->chgSData(oldp+77,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__fractionA),11);
        bufp->chgSData(oldp+78,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__fractionB),11);
        bufp->chgIData(oldp+79,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__fraction),22);
        bufp->chgBit(oldp+80,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__sign));
        bufp->chgCData(oldp+81,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__exponent),6);
        bufp->chgSData(oldp+82,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__mantissa),10);
        bufp->chgSData(oldp+83,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__fractionA),11);
        bufp->chgSData(oldp+84,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__fractionB),11);
        bufp->chgIData(oldp+85,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__fraction),22);
        bufp->chgBit(oldp+86,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__sign));
        bufp->chgCData(oldp+87,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__exponent),6);
        bufp->chgSData(oldp+88,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__mantissa),10);
        bufp->chgSData(oldp+89,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__fractionA),11);
        bufp->chgSData(oldp+90,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__fractionB),11);
        bufp->chgIData(oldp+91,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__fraction),22);
        bufp->chgBit(oldp+92,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__sign));
        bufp->chgCData(oldp+93,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__exponent),6);
        bufp->chgSData(oldp+94,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__mantissa),10);
        bufp->chgSData(oldp+95,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__fractionA),11);
        bufp->chgSData(oldp+96,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__fractionB),11);
        bufp->chgIData(oldp+97,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__fraction),22);
        bufp->chgBit(oldp+98,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__sign));
        bufp->chgCData(oldp+99,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__exponent),6);
        bufp->chgSData(oldp+100,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__mantissa),10);
        bufp->chgSData(oldp+101,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__fractionA),11);
        bufp->chgSData(oldp+102,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__fractionB),11);
        bufp->chgIData(oldp+103,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__fraction),22);
        bufp->chgSData(oldp+104,(vlSelfRef.transformer__DOT__u_mmd__DOT__m00_0),16);
        bufp->chgSData(oldp+105,(vlSelfRef.transformer__DOT__u_mmd__DOT__m00_1),16);
        bufp->chgSData(oldp+106,(vlSelfRef.transformer__DOT__u_mmd__DOT__m01_0),16);
        bufp->chgSData(oldp+107,(vlSelfRef.transformer__DOT__u_mmd__DOT__m01_1),16);
        bufp->chgSData(oldp+108,(vlSelfRef.transformer__DOT__u_mmd__DOT__m10_0),16);
        bufp->chgSData(oldp+109,(vlSelfRef.transformer__DOT__u_mmd__DOT__m10_1),16);
        bufp->chgSData(oldp+110,(vlSelfRef.transformer__DOT__u_mmd__DOT__m11_0),16);
        bufp->chgSData(oldp+111,(vlSelfRef.transformer__DOT__u_mmd__DOT__m11_1),16);
        bufp->chgBit(oldp+112,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__sign));
        bufp->chgCData(oldp+113,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__exponent),6);
        bufp->chgSData(oldp+114,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__mantissa),10);
        bufp->chgCData(oldp+115,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__exponentA),6);
        bufp->chgCData(oldp+116,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__exponentB),6);
        bufp->chgSData(oldp+117,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__fractionA),11);
        bufp->chgSData(oldp+118,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__fractionB),11);
        bufp->chgSData(oldp+119,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__fraction),11);
        bufp->chgCData(oldp+120,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__shiftAmount),8);
        bufp->chgBit(oldp+121,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__cout));
        bufp->chgBit(oldp+122,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__sign));
        bufp->chgCData(oldp+123,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__exponent),6);
        bufp->chgSData(oldp+124,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__mantissa),10);
        bufp->chgCData(oldp+125,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__exponentA),6);
        bufp->chgCData(oldp+126,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__exponentB),6);
        bufp->chgSData(oldp+127,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__fractionA),11);
        bufp->chgSData(oldp+128,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__fractionB),11);
        bufp->chgSData(oldp+129,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__fraction),11);
        bufp->chgCData(oldp+130,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__shiftAmount),8);
        bufp->chgBit(oldp+131,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__cout));
        bufp->chgBit(oldp+132,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__sign));
        bufp->chgCData(oldp+133,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__exponent),6);
        bufp->chgSData(oldp+134,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__mantissa),10);
        bufp->chgCData(oldp+135,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__exponentA),6);
        bufp->chgCData(oldp+136,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__exponentB),6);
        bufp->chgSData(oldp+137,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__fractionA),11);
        bufp->chgSData(oldp+138,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__fractionB),11);
        bufp->chgSData(oldp+139,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__fraction),11);
        bufp->chgCData(oldp+140,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__shiftAmount),8);
        bufp->chgBit(oldp+141,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__cout));
        bufp->chgBit(oldp+142,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__sign));
        bufp->chgCData(oldp+143,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__exponent),6);
        bufp->chgSData(oldp+144,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__mantissa),10);
        bufp->chgCData(oldp+145,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__exponentA),6);
        bufp->chgCData(oldp+146,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__exponentB),6);
        bufp->chgSData(oldp+147,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__fractionA),11);
        bufp->chgSData(oldp+148,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__fractionB),11);
        bufp->chgSData(oldp+149,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__fraction),11);
        bufp->chgCData(oldp+150,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__shiftAmount),8);
        bufp->chgBit(oldp+151,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__cout));
        bufp->chgBit(oldp+152,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__sign));
        bufp->chgCData(oldp+153,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__exponent),6);
        bufp->chgSData(oldp+154,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__mantissa),10);
        bufp->chgSData(oldp+155,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__fractionA),11);
        bufp->chgSData(oldp+156,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__fractionB),11);
        bufp->chgIData(oldp+157,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__fraction),22);
        bufp->chgBit(oldp+158,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__sign));
        bufp->chgCData(oldp+159,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__exponent),6);
        bufp->chgSData(oldp+160,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__mantissa),10);
        bufp->chgSData(oldp+161,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__fractionA),11);
        bufp->chgSData(oldp+162,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__fractionB),11);
        bufp->chgIData(oldp+163,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__fraction),22);
        bufp->chgBit(oldp+164,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__sign));
        bufp->chgCData(oldp+165,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__exponent),6);
        bufp->chgSData(oldp+166,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__mantissa),10);
        bufp->chgSData(oldp+167,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__fractionA),11);
        bufp->chgSData(oldp+168,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__fractionB),11);
        bufp->chgIData(oldp+169,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__fraction),22);
        bufp->chgBit(oldp+170,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__sign));
        bufp->chgCData(oldp+171,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__exponent),6);
        bufp->chgSData(oldp+172,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__mantissa),10);
        bufp->chgSData(oldp+173,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__fractionA),11);
        bufp->chgSData(oldp+174,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__fractionB),11);
        bufp->chgIData(oldp+175,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__fraction),22);
        bufp->chgBit(oldp+176,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__sign));
        bufp->chgCData(oldp+177,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__exponent),6);
        bufp->chgSData(oldp+178,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__mantissa),10);
        bufp->chgSData(oldp+179,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__fractionA),11);
        bufp->chgSData(oldp+180,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__fractionB),11);
        bufp->chgIData(oldp+181,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__fraction),22);
        bufp->chgBit(oldp+182,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__sign));
        bufp->chgCData(oldp+183,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__exponent),6);
        bufp->chgSData(oldp+184,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__mantissa),10);
        bufp->chgSData(oldp+185,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__fractionA),11);
        bufp->chgSData(oldp+186,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__fractionB),11);
        bufp->chgIData(oldp+187,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__fraction),22);
        bufp->chgBit(oldp+188,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__sign));
        bufp->chgCData(oldp+189,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__exponent),6);
        bufp->chgSData(oldp+190,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__mantissa),10);
        bufp->chgSData(oldp+191,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__fractionA),11);
        bufp->chgSData(oldp+192,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__fractionB),11);
        bufp->chgIData(oldp+193,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__fraction),22);
        bufp->chgBit(oldp+194,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__sign));
        bufp->chgCData(oldp+195,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__exponent),6);
        bufp->chgSData(oldp+196,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__mantissa),10);
        bufp->chgSData(oldp+197,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__fractionA),11);
        bufp->chgSData(oldp+198,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__fractionB),11);
        bufp->chgIData(oldp+199,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__fraction),22);
        bufp->chgBit(oldp+200,(vlSelfRef.transformer__DOT__u_mul00__DOT__sign));
        bufp->chgCData(oldp+201,(vlSelfRef.transformer__DOT__u_mul00__DOT__exponent),6);
        bufp->chgSData(oldp+202,(vlSelfRef.transformer__DOT__u_mul00__DOT__mantissa),10);
        bufp->chgSData(oldp+203,(vlSelfRef.transformer__DOT__u_mul00__DOT__fractionA),11);
        bufp->chgSData(oldp+204,(vlSelfRef.transformer__DOT__u_mul00__DOT__fractionB),11);
        bufp->chgIData(oldp+205,(vlSelfRef.transformer__DOT__u_mul00__DOT__fraction),22);
        bufp->chgBit(oldp+206,(vlSelfRef.transformer__DOT__u_mul01__DOT__sign));
        bufp->chgCData(oldp+207,(vlSelfRef.transformer__DOT__u_mul01__DOT__exponent),6);
        bufp->chgSData(oldp+208,(vlSelfRef.transformer__DOT__u_mul01__DOT__mantissa),10);
        bufp->chgSData(oldp+209,(vlSelfRef.transformer__DOT__u_mul01__DOT__fractionA),11);
        bufp->chgSData(oldp+210,(vlSelfRef.transformer__DOT__u_mul01__DOT__fractionB),11);
        bufp->chgIData(oldp+211,(vlSelfRef.transformer__DOT__u_mul01__DOT__fraction),22);
        bufp->chgBit(oldp+212,(vlSelfRef.transformer__DOT__u_mul10__DOT__sign));
        bufp->chgCData(oldp+213,(vlSelfRef.transformer__DOT__u_mul10__DOT__exponent),6);
        bufp->chgSData(oldp+214,(vlSelfRef.transformer__DOT__u_mul10__DOT__mantissa),10);
        bufp->chgSData(oldp+215,(vlSelfRef.transformer__DOT__u_mul10__DOT__fractionA),11);
        bufp->chgSData(oldp+216,(vlSelfRef.transformer__DOT__u_mul10__DOT__fractionB),11);
        bufp->chgIData(oldp+217,(vlSelfRef.transformer__DOT__u_mul10__DOT__fraction),22);
        bufp->chgBit(oldp+218,(vlSelfRef.transformer__DOT__u_mul11__DOT__sign));
        bufp->chgCData(oldp+219,(vlSelfRef.transformer__DOT__u_mul11__DOT__exponent),6);
        bufp->chgSData(oldp+220,(vlSelfRef.transformer__DOT__u_mul11__DOT__mantissa),10);
        bufp->chgSData(oldp+221,(vlSelfRef.transformer__DOT__u_mul11__DOT__fractionA),11);
        bufp->chgSData(oldp+222,(vlSelfRef.transformer__DOT__u_mul11__DOT__fractionB),11);
        bufp->chgIData(oldp+223,(vlSelfRef.transformer__DOT__u_mul11__DOT__fraction),22);
    }
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[2U]))) {
        bufp->chgSData(oldp+224,(vlSelfRef.transformer__DOT__out00_reg),16);
        bufp->chgSData(oldp+225,(vlSelfRef.transformer__DOT__out01_reg),16);
        bufp->chgSData(oldp+226,(vlSelfRef.transformer__DOT__out10_reg),16);
        bufp->chgSData(oldp+227,(vlSelfRef.transformer__DOT__out11_reg),16);
    }
    bufp->chgSData(oldp+228,(vlSelfRef.q00),16);
    bufp->chgSData(oldp+229,(vlSelfRef.q01),16);
    bufp->chgSData(oldp+230,(vlSelfRef.q10),16);
    bufp->chgSData(oldp+231,(vlSelfRef.q11),16);
    bufp->chgSData(oldp+232,(vlSelfRef.k00),16);
    bufp->chgSData(oldp+233,(vlSelfRef.k01),16);
    bufp->chgSData(oldp+234,(vlSelfRef.k10),16);
    bufp->chgSData(oldp+235,(vlSelfRef.k11),16);
    bufp->chgSData(oldp+236,(vlSelfRef.v00),16);
    bufp->chgSData(oldp+237,(vlSelfRef.v01),16);
    bufp->chgSData(oldp+238,(vlSelfRef.v10),16);
    bufp->chgSData(oldp+239,(vlSelfRef.v11),16);
    bufp->chgBit(oldp+240,(vlSelfRef.clk));
    bufp->chgSData(oldp+241,(vlSelfRef.out00),16);
    bufp->chgSData(oldp+242,(vlSelfRef.out01),16);
    bufp->chgSData(oldp+243,(vlSelfRef.out10),16);
    bufp->chgSData(oldp+244,(vlSelfRef.out11),16);
}

void Vtransformer___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_cleanup\n"); );
    // Init
    Vtransformer___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtransformer___024root*>(voidSelf);
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
}
