// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtransformer__Syms.h"


VL_ATTR_COLD void Vtransformer___024root__trace_init_sub__TOP__0(Vtransformer___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_init_sub__TOP__0\n"); );
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+229,0,"q00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+230,0,"q01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+231,0,"q10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+232,0,"q11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+233,0,"k00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+234,0,"k01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+235,0,"k10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+236,0,"k11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+237,0,"v00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+238,0,"v01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+239,0,"v10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+240,0,"v11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+241,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+242,0,"out00",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+243,0,"out01",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+244,0,"out10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+245,0,"out11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("transformer", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+229,0,"q00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+230,0,"q01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+231,0,"q10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+232,0,"q11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+233,0,"k00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+234,0,"k01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+235,0,"k10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+236,0,"k11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+237,0,"v00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+238,0,"v01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+239,0,"v10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+240,0,"v11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+241,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+242,0,"out00",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+243,0,"out01",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+244,0,"out10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+245,0,"out11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+1,0,"qk00_raw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+2,0,"qk01_raw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+3,0,"qk10_raw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+4,0,"qk11_raw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+246,0,"SCALE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+5,0,"qk00",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+6,0,"qk01",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+7,0,"qk10",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+8,0,"qk11",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+225,0,"out00_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+226,0,"out01_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+227,0,"out10_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+228,0,"out11_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("u_mma", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+229,0,"a00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+230,0,"a01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+231,0,"a10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+232,0,"a11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+233,0,"b00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+235,0,"b10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+234,0,"b01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+236,0,"b11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+1,0,"out00",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+2,0,"out01",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+3,0,"out10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+4,0,"out11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+9,0,"m00_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+10,0,"m00_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+11,0,"m01_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+12,0,"m01_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+13,0,"m10_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+14,0,"m10_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+15,0,"m11_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+16,0,"m11_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("add00", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+9,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+10,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+1,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+17,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+18,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+19,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+20,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+21,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+22,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+23,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+24,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+25,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+26,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("add01", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+11,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+12,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+2,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+27,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+28,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+29,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+30,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+31,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+32,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+33,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+34,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+35,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+36,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("add10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+13,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+14,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+3,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+37,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+38,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+39,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+40,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+41,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+42,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+43,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+44,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+45,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+46,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("add11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+15,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+16,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+4,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+47,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+48,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+49,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+50,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+51,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+52,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+53,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+54,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+55,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+56,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("mul00_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+229,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+233,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+9,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+57,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+58,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+59,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+60,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+61,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+62,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul00_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+230,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+235,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+10,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+63,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+64,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+65,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+66,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+67,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+68,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul01_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+229,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+234,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+11,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+69,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+71,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+72,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+73,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+74,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul01_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+230,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+236,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+12,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+75,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+77,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+78,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+79,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+80,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul10_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+231,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+233,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+13,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+81,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+82,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+83,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+84,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+85,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+86,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul10_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+232,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+235,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+14,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+87,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+88,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+89,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+90,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+91,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+92,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul11_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+231,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+234,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+15,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+93,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+94,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+95,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+96,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+97,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+98,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul11_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+232,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+236,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+16,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+99,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+100,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+101,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+102,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+103,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+104,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_mmd", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+5,0,"a00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+6,0,"a01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+7,0,"a10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+8,0,"a11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+237,0,"v00",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+238,0,"v01",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+239,0,"v10",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+240,0,"v11",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+242,0,"out00",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+243,0,"out01",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+244,0,"out10",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+245,0,"out11",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+105,0,"m00_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+106,0,"m00_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+107,0,"m01_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+108,0,"m01_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+109,0,"m10_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+110,0,"m10_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+111,0,"m11_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+112,0,"m11_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("add00", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+105,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+106,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+242,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+113,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+114,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+115,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+116,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+117,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+118,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+119,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+120,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+121,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+122,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("add01", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+107,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+108,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+243,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+123,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+125,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+126,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+127,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+128,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+129,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+130,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+131,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+132,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("add10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+109,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+110,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+244,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+133,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+134,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+135,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+136,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+137,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+138,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+139,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+140,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+141,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+142,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("add11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+111,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+112,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+245,0,"sum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+143,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+144,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+145,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+146,0,"exponentA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+147,0,"exponentB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+148,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+149,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+150,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+151,0,"shiftAmount",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+152,0,"cout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("mul00_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+5,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+237,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+105,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+153,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+154,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+155,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+156,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+157,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+158,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul00_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+6,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+239,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+106,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+159,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+160,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+161,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+162,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+163,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+164,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul01_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+5,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+238,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+107,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+165,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+166,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+167,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+168,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+169,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+170,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul01_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+6,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+240,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+108,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+171,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+172,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+173,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+174,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+175,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+176,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul10_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+7,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+237,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+109,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+177,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+178,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+179,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+180,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+181,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+182,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul10_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+8,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+239,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+110,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+183,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+184,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+185,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+186,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+187,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+188,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul11_0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+7,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+238,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+111,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+189,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+190,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+191,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+192,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+193,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+194,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("mul11_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+8,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+240,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+112,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+195,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+196,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+197,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+198,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+199,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+200,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_mul00", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+1,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+246,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+5,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+201,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+202,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+203,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+204,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+205,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+206,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_mul01", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+2,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+246,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+6,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+207,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+208,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+209,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+210,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+211,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+212,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_mul10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+3,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+246,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+7,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+213,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+214,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+215,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+216,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+217,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+218,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_mul11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+4,0,"floatA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+246,0,"floatB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+8,0,"product",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+219,0,"sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+220,0,"exponent",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+221,0,"mantissa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+222,0,"fractionA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+223,0,"fractionB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+224,0,"fraction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtransformer___024root__trace_init_top(Vtransformer___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_init_top\n"); );
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtransformer___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtransformer___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtransformer___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtransformer___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtransformer___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtransformer___024root__trace_register(Vtransformer___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_register\n"); );
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtransformer___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtransformer___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtransformer___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtransformer___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtransformer___024root__trace_const_0_sub_0(Vtransformer___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtransformer___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_const_0\n"); );
    // Init
    Vtransformer___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtransformer___024root*>(voidSelf);
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtransformer___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtransformer___024root__trace_const_0_sub_0(Vtransformer___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_const_0_sub_0\n"); );
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullSData(oldp+246,(0x3800U),16);
}

VL_ATTR_COLD void Vtransformer___024root__trace_full_0_sub_0(Vtransformer___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtransformer___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_full_0\n"); );
    // Init
    Vtransformer___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtransformer___024root*>(voidSelf);
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtransformer___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtransformer___024root__trace_full_0_sub_0(Vtransformer___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtransformer___024root__trace_full_0_sub_0\n"); );
    Vtransformer__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullSData(oldp+1,(vlSelfRef.transformer__DOT__qk00_raw),16);
    bufp->fullSData(oldp+2,(vlSelfRef.transformer__DOT__qk01_raw),16);
    bufp->fullSData(oldp+3,(vlSelfRef.transformer__DOT__qk10_raw),16);
    bufp->fullSData(oldp+4,(vlSelfRef.transformer__DOT__qk11_raw),16);
    bufp->fullSData(oldp+5,(vlSelfRef.transformer__DOT__qk00),16);
    bufp->fullSData(oldp+6,(vlSelfRef.transformer__DOT__qk01),16);
    bufp->fullSData(oldp+7,(vlSelfRef.transformer__DOT__qk10),16);
    bufp->fullSData(oldp+8,(vlSelfRef.transformer__DOT__qk11),16);
    bufp->fullSData(oldp+9,(vlSelfRef.transformer__DOT__u_mma__DOT__m00_0),16);
    bufp->fullSData(oldp+10,(vlSelfRef.transformer__DOT__u_mma__DOT__m00_1),16);
    bufp->fullSData(oldp+11,(vlSelfRef.transformer__DOT__u_mma__DOT__m01_0),16);
    bufp->fullSData(oldp+12,(vlSelfRef.transformer__DOT__u_mma__DOT__m01_1),16);
    bufp->fullSData(oldp+13,(vlSelfRef.transformer__DOT__u_mma__DOT__m10_0),16);
    bufp->fullSData(oldp+14,(vlSelfRef.transformer__DOT__u_mma__DOT__m10_1),16);
    bufp->fullSData(oldp+15,(vlSelfRef.transformer__DOT__u_mma__DOT__m11_0),16);
    bufp->fullSData(oldp+16,(vlSelfRef.transformer__DOT__u_mma__DOT__m11_1),16);
    bufp->fullBit(oldp+17,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__sign));
    bufp->fullCData(oldp+18,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__exponent),6);
    bufp->fullSData(oldp+19,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__mantissa),10);
    bufp->fullCData(oldp+20,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__exponentA),6);
    bufp->fullCData(oldp+21,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__exponentB),6);
    bufp->fullSData(oldp+22,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__fractionA),11);
    bufp->fullSData(oldp+23,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__fractionB),11);
    bufp->fullSData(oldp+24,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__fraction),11);
    bufp->fullCData(oldp+25,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__shiftAmount),8);
    bufp->fullBit(oldp+26,(vlSelfRef.transformer__DOT__u_mma__DOT__add00__DOT__cout));
    bufp->fullBit(oldp+27,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__sign));
    bufp->fullCData(oldp+28,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__exponent),6);
    bufp->fullSData(oldp+29,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__mantissa),10);
    bufp->fullCData(oldp+30,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__exponentA),6);
    bufp->fullCData(oldp+31,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__exponentB),6);
    bufp->fullSData(oldp+32,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__fractionA),11);
    bufp->fullSData(oldp+33,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__fractionB),11);
    bufp->fullSData(oldp+34,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__fraction),11);
    bufp->fullCData(oldp+35,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__shiftAmount),8);
    bufp->fullBit(oldp+36,(vlSelfRef.transformer__DOT__u_mma__DOT__add01__DOT__cout));
    bufp->fullBit(oldp+37,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__sign));
    bufp->fullCData(oldp+38,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__exponent),6);
    bufp->fullSData(oldp+39,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__mantissa),10);
    bufp->fullCData(oldp+40,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__exponentA),6);
    bufp->fullCData(oldp+41,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__exponentB),6);
    bufp->fullSData(oldp+42,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__fractionA),11);
    bufp->fullSData(oldp+43,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__fractionB),11);
    bufp->fullSData(oldp+44,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__fraction),11);
    bufp->fullCData(oldp+45,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__shiftAmount),8);
    bufp->fullBit(oldp+46,(vlSelfRef.transformer__DOT__u_mma__DOT__add10__DOT__cout));
    bufp->fullBit(oldp+47,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__sign));
    bufp->fullCData(oldp+48,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__exponent),6);
    bufp->fullSData(oldp+49,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__mantissa),10);
    bufp->fullCData(oldp+50,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__exponentA),6);
    bufp->fullCData(oldp+51,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__exponentB),6);
    bufp->fullSData(oldp+52,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__fractionA),11);
    bufp->fullSData(oldp+53,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__fractionB),11);
    bufp->fullSData(oldp+54,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__fraction),11);
    bufp->fullCData(oldp+55,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__shiftAmount),8);
    bufp->fullBit(oldp+56,(vlSelfRef.transformer__DOT__u_mma__DOT__add11__DOT__cout));
    bufp->fullBit(oldp+57,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__sign));
    bufp->fullCData(oldp+58,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__exponent),6);
    bufp->fullSData(oldp+59,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__mantissa),10);
    bufp->fullSData(oldp+60,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__fractionA),11);
    bufp->fullSData(oldp+61,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__fractionB),11);
    bufp->fullIData(oldp+62,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_0__DOT__fraction),22);
    bufp->fullBit(oldp+63,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__sign));
    bufp->fullCData(oldp+64,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__exponent),6);
    bufp->fullSData(oldp+65,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__mantissa),10);
    bufp->fullSData(oldp+66,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__fractionA),11);
    bufp->fullSData(oldp+67,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__fractionB),11);
    bufp->fullIData(oldp+68,(vlSelfRef.transformer__DOT__u_mma__DOT__mul00_1__DOT__fraction),22);
    bufp->fullBit(oldp+69,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__sign));
    bufp->fullCData(oldp+70,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__exponent),6);
    bufp->fullSData(oldp+71,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__mantissa),10);
    bufp->fullSData(oldp+72,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__fractionA),11);
    bufp->fullSData(oldp+73,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__fractionB),11);
    bufp->fullIData(oldp+74,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_0__DOT__fraction),22);
    bufp->fullBit(oldp+75,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__sign));
    bufp->fullCData(oldp+76,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__exponent),6);
    bufp->fullSData(oldp+77,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__mantissa),10);
    bufp->fullSData(oldp+78,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__fractionA),11);
    bufp->fullSData(oldp+79,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__fractionB),11);
    bufp->fullIData(oldp+80,(vlSelfRef.transformer__DOT__u_mma__DOT__mul01_1__DOT__fraction),22);
    bufp->fullBit(oldp+81,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__sign));
    bufp->fullCData(oldp+82,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__exponent),6);
    bufp->fullSData(oldp+83,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__mantissa),10);
    bufp->fullSData(oldp+84,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__fractionA),11);
    bufp->fullSData(oldp+85,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__fractionB),11);
    bufp->fullIData(oldp+86,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_0__DOT__fraction),22);
    bufp->fullBit(oldp+87,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__sign));
    bufp->fullCData(oldp+88,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__exponent),6);
    bufp->fullSData(oldp+89,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__mantissa),10);
    bufp->fullSData(oldp+90,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__fractionA),11);
    bufp->fullSData(oldp+91,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__fractionB),11);
    bufp->fullIData(oldp+92,(vlSelfRef.transformer__DOT__u_mma__DOT__mul10_1__DOT__fraction),22);
    bufp->fullBit(oldp+93,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__sign));
    bufp->fullCData(oldp+94,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__exponent),6);
    bufp->fullSData(oldp+95,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__mantissa),10);
    bufp->fullSData(oldp+96,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__fractionA),11);
    bufp->fullSData(oldp+97,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__fractionB),11);
    bufp->fullIData(oldp+98,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_0__DOT__fraction),22);
    bufp->fullBit(oldp+99,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__sign));
    bufp->fullCData(oldp+100,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__exponent),6);
    bufp->fullSData(oldp+101,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__mantissa),10);
    bufp->fullSData(oldp+102,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__fractionA),11);
    bufp->fullSData(oldp+103,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__fractionB),11);
    bufp->fullIData(oldp+104,(vlSelfRef.transformer__DOT__u_mma__DOT__mul11_1__DOT__fraction),22);
    bufp->fullSData(oldp+105,(vlSelfRef.transformer__DOT__u_mmd__DOT__m00_0),16);
    bufp->fullSData(oldp+106,(vlSelfRef.transformer__DOT__u_mmd__DOT__m00_1),16);
    bufp->fullSData(oldp+107,(vlSelfRef.transformer__DOT__u_mmd__DOT__m01_0),16);
    bufp->fullSData(oldp+108,(vlSelfRef.transformer__DOT__u_mmd__DOT__m01_1),16);
    bufp->fullSData(oldp+109,(vlSelfRef.transformer__DOT__u_mmd__DOT__m10_0),16);
    bufp->fullSData(oldp+110,(vlSelfRef.transformer__DOT__u_mmd__DOT__m10_1),16);
    bufp->fullSData(oldp+111,(vlSelfRef.transformer__DOT__u_mmd__DOT__m11_0),16);
    bufp->fullSData(oldp+112,(vlSelfRef.transformer__DOT__u_mmd__DOT__m11_1),16);
    bufp->fullBit(oldp+113,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__sign));
    bufp->fullCData(oldp+114,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__exponent),6);
    bufp->fullSData(oldp+115,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__mantissa),10);
    bufp->fullCData(oldp+116,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__exponentA),6);
    bufp->fullCData(oldp+117,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__exponentB),6);
    bufp->fullSData(oldp+118,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__fractionA),11);
    bufp->fullSData(oldp+119,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__fractionB),11);
    bufp->fullSData(oldp+120,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__fraction),11);
    bufp->fullCData(oldp+121,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__shiftAmount),8);
    bufp->fullBit(oldp+122,(vlSelfRef.transformer__DOT__u_mmd__DOT__add00__DOT__cout));
    bufp->fullBit(oldp+123,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__sign));
    bufp->fullCData(oldp+124,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__exponent),6);
    bufp->fullSData(oldp+125,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__mantissa),10);
    bufp->fullCData(oldp+126,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__exponentA),6);
    bufp->fullCData(oldp+127,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__exponentB),6);
    bufp->fullSData(oldp+128,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__fractionA),11);
    bufp->fullSData(oldp+129,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__fractionB),11);
    bufp->fullSData(oldp+130,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__fraction),11);
    bufp->fullCData(oldp+131,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__shiftAmount),8);
    bufp->fullBit(oldp+132,(vlSelfRef.transformer__DOT__u_mmd__DOT__add01__DOT__cout));
    bufp->fullBit(oldp+133,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__sign));
    bufp->fullCData(oldp+134,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__exponent),6);
    bufp->fullSData(oldp+135,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__mantissa),10);
    bufp->fullCData(oldp+136,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__exponentA),6);
    bufp->fullCData(oldp+137,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__exponentB),6);
    bufp->fullSData(oldp+138,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__fractionA),11);
    bufp->fullSData(oldp+139,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__fractionB),11);
    bufp->fullSData(oldp+140,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__fraction),11);
    bufp->fullCData(oldp+141,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__shiftAmount),8);
    bufp->fullBit(oldp+142,(vlSelfRef.transformer__DOT__u_mmd__DOT__add10__DOT__cout));
    bufp->fullBit(oldp+143,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__sign));
    bufp->fullCData(oldp+144,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__exponent),6);
    bufp->fullSData(oldp+145,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__mantissa),10);
    bufp->fullCData(oldp+146,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__exponentA),6);
    bufp->fullCData(oldp+147,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__exponentB),6);
    bufp->fullSData(oldp+148,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__fractionA),11);
    bufp->fullSData(oldp+149,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__fractionB),11);
    bufp->fullSData(oldp+150,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__fraction),11);
    bufp->fullCData(oldp+151,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__shiftAmount),8);
    bufp->fullBit(oldp+152,(vlSelfRef.transformer__DOT__u_mmd__DOT__add11__DOT__cout));
    bufp->fullBit(oldp+153,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__sign));
    bufp->fullCData(oldp+154,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__exponent),6);
    bufp->fullSData(oldp+155,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__mantissa),10);
    bufp->fullSData(oldp+156,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__fractionA),11);
    bufp->fullSData(oldp+157,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__fractionB),11);
    bufp->fullIData(oldp+158,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_0__DOT__fraction),22);
    bufp->fullBit(oldp+159,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__sign));
    bufp->fullCData(oldp+160,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__exponent),6);
    bufp->fullSData(oldp+161,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__mantissa),10);
    bufp->fullSData(oldp+162,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__fractionA),11);
    bufp->fullSData(oldp+163,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__fractionB),11);
    bufp->fullIData(oldp+164,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul00_1__DOT__fraction),22);
    bufp->fullBit(oldp+165,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__sign));
    bufp->fullCData(oldp+166,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__exponent),6);
    bufp->fullSData(oldp+167,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__mantissa),10);
    bufp->fullSData(oldp+168,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__fractionA),11);
    bufp->fullSData(oldp+169,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__fractionB),11);
    bufp->fullIData(oldp+170,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_0__DOT__fraction),22);
    bufp->fullBit(oldp+171,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__sign));
    bufp->fullCData(oldp+172,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__exponent),6);
    bufp->fullSData(oldp+173,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__mantissa),10);
    bufp->fullSData(oldp+174,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__fractionA),11);
    bufp->fullSData(oldp+175,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__fractionB),11);
    bufp->fullIData(oldp+176,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul01_1__DOT__fraction),22);
    bufp->fullBit(oldp+177,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__sign));
    bufp->fullCData(oldp+178,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__exponent),6);
    bufp->fullSData(oldp+179,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__mantissa),10);
    bufp->fullSData(oldp+180,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__fractionA),11);
    bufp->fullSData(oldp+181,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__fractionB),11);
    bufp->fullIData(oldp+182,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_0__DOT__fraction),22);
    bufp->fullBit(oldp+183,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__sign));
    bufp->fullCData(oldp+184,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__exponent),6);
    bufp->fullSData(oldp+185,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__mantissa),10);
    bufp->fullSData(oldp+186,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__fractionA),11);
    bufp->fullSData(oldp+187,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__fractionB),11);
    bufp->fullIData(oldp+188,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul10_1__DOT__fraction),22);
    bufp->fullBit(oldp+189,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__sign));
    bufp->fullCData(oldp+190,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__exponent),6);
    bufp->fullSData(oldp+191,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__mantissa),10);
    bufp->fullSData(oldp+192,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__fractionA),11);
    bufp->fullSData(oldp+193,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__fractionB),11);
    bufp->fullIData(oldp+194,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_0__DOT__fraction),22);
    bufp->fullBit(oldp+195,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__sign));
    bufp->fullCData(oldp+196,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__exponent),6);
    bufp->fullSData(oldp+197,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__mantissa),10);
    bufp->fullSData(oldp+198,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__fractionA),11);
    bufp->fullSData(oldp+199,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__fractionB),11);
    bufp->fullIData(oldp+200,(vlSelfRef.transformer__DOT__u_mmd__DOT__mul11_1__DOT__fraction),22);
    bufp->fullBit(oldp+201,(vlSelfRef.transformer__DOT__u_mul00__DOT__sign));
    bufp->fullCData(oldp+202,(vlSelfRef.transformer__DOT__u_mul00__DOT__exponent),6);
    bufp->fullSData(oldp+203,(vlSelfRef.transformer__DOT__u_mul00__DOT__mantissa),10);
    bufp->fullSData(oldp+204,(vlSelfRef.transformer__DOT__u_mul00__DOT__fractionA),11);
    bufp->fullSData(oldp+205,(vlSelfRef.transformer__DOT__u_mul00__DOT__fractionB),11);
    bufp->fullIData(oldp+206,(vlSelfRef.transformer__DOT__u_mul00__DOT__fraction),22);
    bufp->fullBit(oldp+207,(vlSelfRef.transformer__DOT__u_mul01__DOT__sign));
    bufp->fullCData(oldp+208,(vlSelfRef.transformer__DOT__u_mul01__DOT__exponent),6);
    bufp->fullSData(oldp+209,(vlSelfRef.transformer__DOT__u_mul01__DOT__mantissa),10);
    bufp->fullSData(oldp+210,(vlSelfRef.transformer__DOT__u_mul01__DOT__fractionA),11);
    bufp->fullSData(oldp+211,(vlSelfRef.transformer__DOT__u_mul01__DOT__fractionB),11);
    bufp->fullIData(oldp+212,(vlSelfRef.transformer__DOT__u_mul01__DOT__fraction),22);
    bufp->fullBit(oldp+213,(vlSelfRef.transformer__DOT__u_mul10__DOT__sign));
    bufp->fullCData(oldp+214,(vlSelfRef.transformer__DOT__u_mul10__DOT__exponent),6);
    bufp->fullSData(oldp+215,(vlSelfRef.transformer__DOT__u_mul10__DOT__mantissa),10);
    bufp->fullSData(oldp+216,(vlSelfRef.transformer__DOT__u_mul10__DOT__fractionA),11);
    bufp->fullSData(oldp+217,(vlSelfRef.transformer__DOT__u_mul10__DOT__fractionB),11);
    bufp->fullIData(oldp+218,(vlSelfRef.transformer__DOT__u_mul10__DOT__fraction),22);
    bufp->fullBit(oldp+219,(vlSelfRef.transformer__DOT__u_mul11__DOT__sign));
    bufp->fullCData(oldp+220,(vlSelfRef.transformer__DOT__u_mul11__DOT__exponent),6);
    bufp->fullSData(oldp+221,(vlSelfRef.transformer__DOT__u_mul11__DOT__mantissa),10);
    bufp->fullSData(oldp+222,(vlSelfRef.transformer__DOT__u_mul11__DOT__fractionA),11);
    bufp->fullSData(oldp+223,(vlSelfRef.transformer__DOT__u_mul11__DOT__fractionB),11);
    bufp->fullIData(oldp+224,(vlSelfRef.transformer__DOT__u_mul11__DOT__fraction),22);
    bufp->fullSData(oldp+225,(vlSelfRef.transformer__DOT__out00_reg),16);
    bufp->fullSData(oldp+226,(vlSelfRef.transformer__DOT__out01_reg),16);
    bufp->fullSData(oldp+227,(vlSelfRef.transformer__DOT__out10_reg),16);
    bufp->fullSData(oldp+228,(vlSelfRef.transformer__DOT__out11_reg),16);
    bufp->fullSData(oldp+229,(vlSelfRef.q00),16);
    bufp->fullSData(oldp+230,(vlSelfRef.q01),16);
    bufp->fullSData(oldp+231,(vlSelfRef.q10),16);
    bufp->fullSData(oldp+232,(vlSelfRef.q11),16);
    bufp->fullSData(oldp+233,(vlSelfRef.k00),16);
    bufp->fullSData(oldp+234,(vlSelfRef.k01),16);
    bufp->fullSData(oldp+235,(vlSelfRef.k10),16);
    bufp->fullSData(oldp+236,(vlSelfRef.k11),16);
    bufp->fullSData(oldp+237,(vlSelfRef.v00),16);
    bufp->fullSData(oldp+238,(vlSelfRef.v01),16);
    bufp->fullSData(oldp+239,(vlSelfRef.v10),16);
    bufp->fullSData(oldp+240,(vlSelfRef.v11),16);
    bufp->fullBit(oldp+241,(vlSelfRef.clk));
    bufp->fullSData(oldp+242,(vlSelfRef.out00),16);
    bufp->fullSData(oldp+243,(vlSelfRef.out01),16);
    bufp->fullSData(oldp+244,(vlSelfRef.out10),16);
    bufp->fullSData(oldp+245,(vlSelfRef.out11),16);
}
