// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtransformer.h for the primary calling header

#ifndef VERILATED_VTRANSFORMER___024ROOT_H_
#define VERILATED_VTRANSFORMER___024ROOT_H_  // guard

#include "verilated.h"


class Vtransformer__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtransformer___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul00_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul00_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul00_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul00_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul01_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul01_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul01_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul01_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul10_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul10_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul10_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul10_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul11_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul11_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__mul11_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__mul11_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add00__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add00__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add00__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add00__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mma__DOT__add00__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add00__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add00__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add01__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add01__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add01__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add01__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mma__DOT__add01__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add01__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add01__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add10__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add10__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add10__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add10__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mma__DOT__add10__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add10__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add10__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add11__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add11__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add11__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mma__DOT__add11__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mma__DOT__add11__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add11__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mma__DOT__add11__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mul00__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mul00__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mul01__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mul01__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mul10__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mul10__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mul11__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mul11__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul00_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul00_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul00_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul00_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul01_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul01_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul01_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul01_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul10_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul10_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul10_1__DOT__sign;
    };
    struct {
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul10_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul11_0__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul11_0__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__mul11_1__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__mul11_1__DOT__exponent;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add00__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add01__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add10__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__sign;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__exponent;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__exponentA;
        CData/*5:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__exponentB;
        CData/*7:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__shiftAmount;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__cout;
        CData/*0:0*/ transformer__DOT__u_mmd__DOT__add11__DOT____Vconcswap_1_h8e53a22f__0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(q00,15,0);
        VL_IN16(q01,15,0);
        VL_IN16(q10,15,0);
        VL_IN16(q11,15,0);
        VL_IN16(k00,15,0);
        VL_IN16(k01,15,0);
        VL_IN16(k10,15,0);
        VL_IN16(k11,15,0);
        VL_IN16(v00,15,0);
        VL_IN16(v01,15,0);
        VL_IN16(v10,15,0);
        VL_IN16(v11,15,0);
        VL_OUT16(out00,15,0);
        VL_OUT16(out01,15,0);
        VL_OUT16(out10,15,0);
        VL_OUT16(out11,15,0);
        SData/*15:0*/ transformer__DOT__qk00_raw;
        SData/*15:0*/ transformer__DOT__qk01_raw;
        SData/*15:0*/ transformer__DOT__qk10_raw;
        SData/*15:0*/ transformer__DOT__qk11_raw;
        SData/*15:0*/ transformer__DOT__qk00;
        SData/*15:0*/ transformer__DOT__qk01;
        SData/*15:0*/ transformer__DOT__qk10;
        SData/*15:0*/ transformer__DOT__qk11;
        SData/*15:0*/ transformer__DOT__out00_reg;
        SData/*15:0*/ transformer__DOT__out01_reg;
        SData/*15:0*/ transformer__DOT__out10_reg;
    };
    struct {
        SData/*15:0*/ transformer__DOT__out11_reg;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m00_0;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m00_1;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m01_0;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m01_1;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m10_0;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m10_1;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m11_0;
        SData/*15:0*/ transformer__DOT__u_mma__DOT__m11_1;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul00_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul00_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul00_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul00_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul00_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul00_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul01_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul01_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul01_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul01_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul01_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul01_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul10_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul10_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul10_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul10_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul10_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul10_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul11_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul11_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul11_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__mul11_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul11_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__mul11_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__add00__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add00__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add00__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add00__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add00__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__add01__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add01__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add01__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add01__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add01__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__add10__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add10__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add10__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add10__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add10__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mma__DOT__add11__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add11__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add11__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add11__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mma__DOT__add11__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mul00__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mul00__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mul00__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mul01__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mul01__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mul01__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mul10__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mul10__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mul10__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mul11__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mul11__DOT__fractionA;
    };
    struct {
        SData/*10:0*/ transformer__DOT__u_mul11__DOT__fractionB;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m00_0;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m00_1;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m01_0;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m01_1;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m10_0;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m10_1;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m11_0;
        SData/*15:0*/ transformer__DOT__u_mmd__DOT__m11_1;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul00_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul00_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul00_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul00_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul00_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul00_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul01_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul01_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul01_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul01_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul01_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul01_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul10_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul10_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul10_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul10_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul10_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul10_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul11_0__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul11_0__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul11_0__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__mul11_1__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul11_1__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__mul11_1__DOT__fractionB;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add00__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add00__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add01__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add01__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add10__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add10__DOT____Vconcswap_1_h55214352__0;
        SData/*9:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__mantissa;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__fractionA;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__fractionB;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add11__DOT__fraction;
        SData/*10:0*/ transformer__DOT__u_mmd__DOT__add11__DOT____Vconcswap_1_h55214352__0;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul00_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul00_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul01_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul01_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul10_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul10_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul11_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mma__DOT__mul11_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mul00__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mul01__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mul10__DOT__fraction;
    };
    struct {
        IData/*21:0*/ transformer__DOT__u_mul11__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul00_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul00_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul01_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul01_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul10_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul10_1__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul11_0__DOT__fraction;
        IData/*21:0*/ transformer__DOT__u_mmd__DOT__mul11_1__DOT__fraction;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtransformer__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtransformer___024root(Vtransformer__Syms* symsp, const char* v__name);
    ~Vtransformer___024root();
    VL_UNCOPYABLE(Vtransformer___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
